// <auto-generated />
using System;
using Fresenius_Angular.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Fresenius_Angular.Migrations
{
    [DbContext(typeof(FreseniusContext))]
    partial class FreseniusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Fresenius_Angular.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<byte[]>("Image_Byte");

                    b.Property<string>("Name");

                    b.Property<string>("RegNumber");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.IdentityCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Applicant");

                    b.Property<DateTime>("DateOfRegistration");

                    b.Property<DateTime>("Expiration");

                    b.Property<string>("Number");

                    b.Property<string>("Purpose");

                    b.HasKey("Id");

                    b.ToTable("IdentityCards");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<string>("Num");

                    b.Property<string>("Recipient");

                    b.Property<string>("Sender");

                    b.Property<int[]>("SparePartsInInvoice");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdressOfDeparture");

                    b.Property<string>("Code");

                    b.Property<string>("Logo");

                    b.Property<byte[]>("LogoFoto");

                    b.Property<string>("NameFull");

                    b.Property<string>("NameShort");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.ProductName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Designation");

                    b.Property<string>("Gost");

                    b.Property<int>("Item");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("RegItem");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ProductNames");
                });

            modelBuilder.Entity("Fresenius_Angular.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CountryId");

                    b.Property<string>("Description");

                    b.Property<int?>("EquipmentId");

                    b.Property<string>("Image");

                    b.Property<byte[]>("Image_Byte");

                    b.Property<int[]>("InvoiceID");

                    b.Property<int?>("ManufacturerId");

                    b.Property<string>("NameEn");

                    b.Property<string>("NameRus");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("Spareparts");
                });
#pragma warning restore 612, 618
        }
    }
}
